# lo pirmero es dar un name a este workflow/a esta acción
name: tests-auth

# On determina cuando ejecutar el script
on:
  pull_request:
    paths:
      - 'auth/**'

# jobs determina que tareas realizar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
