# lo pirmero es dar un name a este workflow/a esta acción
name: tests-orders

# On determina cuando ejecutar el script
on:
  pull_request

# jobs determina que tareas realizar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
